import { useState, useRef } from 'react';
import { useWelfare } from '@/context/WelfareContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Upload, FileText, Download, CheckCircle2, Image as ImageIcon, ArrowUp, Bot } from 'lucide-react';
import { jsPDF } from 'jspdf';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { PreparedDocument } from '@/types/welfare';

const DocPrepChat = () => {
  const {
    docPrepSession, setDocPrepUserName, addPreparedDoc, advanceDocPrep,
    addTerminalLog, addChatMessage, clearDocPrep,
  } = useWelfare();
  const [nameInput, setNameInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  if (!docPrepSession) return null;

  const { programName, userName, docs, currentDocIndex, preparedDocs, status } = docPrepSession;

  const handleNameSubmit = () => {
    if (!nameInput.trim()) return;
    setDocPrepUserName(nameInput.trim());
    addTerminalLog(`[DocPrep] 用户姓名: ${nameInput.trim()}`);
    setNameInput('');
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || currentDocIndex >= docs.length) return;

    setIsGenerating(true);
    const docLabel = docs[currentDocIndex];
    addTerminalLog(`[DocPrep] 正在为 "${docLabel}" 生成PDF...`);

    try {
      const imageDataUrl = await readFileAsDataUrl(file);
      const pdfBlob = await generatePDF(docLabel, userName, imageDataUrl);
      const fileName = `${docLabel} - ${userName}.pdf`;

      const prepDoc: PreparedDocument = { docLabel, fileName, pdfBlob, imageDataUrl };
      addPreparedDoc(prepDoc);
      advanceDocPrep();
      addTerminalLog(`[DocPrep] ✓ "${fileName}" 已生成。`);
    } catch (err) {
      addTerminalLog(`[DocPrep] 生成PDF失败: ${err}`);
    } finally {
      setIsGenerating(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const readFileAsDataUrl = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const generatePDF = async (docLabel: string, name: string, imageDataUrl: string): Promise<Blob> => {
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();

    // Title - Times Roman, 14pt, centered, bold
    pdf.setFontSize(14);
    pdf.setFont('times', 'bold');
    const title = `${docLabel} - ${name}`;
    pdf.text(title, pageWidth / 2, 25, { align: 'center' });

    // Separator line
    pdf.setDrawColor(200, 200, 200);
    pdf.line(20, 30, pageWidth - 20, 30);

    // Add image - fit within page with margins
    const img = new Image();
    img.src = imageDataUrl;
    await new Promise<void>((resolve) => { img.onload = () => resolve(); });

    const maxW = pageWidth - 40;
    const maxH = 220;
    let imgW = img.width;
    let imgH = img.height;
    const ratio = Math.min(maxW / imgW, maxH / imgH);
    imgW *= ratio;
    imgH *= ratio;

    const x = (pageWidth - imgW) / 2;
    pdf.addImage(imageDataUrl, 'JPEG', x, 36, imgW, imgH);

    // Footer
    pdf.setFontSize(8);
    pdf.setFont('times', 'normal');
    pdf.setTextColor(150);
    pdf.text(`Generated by WelfareAI - ${new Date().toLocaleDateString()}`, pageWidth / 2, 285, { align: 'center' });

    return pdf.output('blob');
  };

  const handleDownloadAll = async () => {
    if (preparedDocs.length === 0) return;
    addTerminalLog(`[DocPrep] 正在打包ZIP...`);

    const zip = new JSZip();
    const folderName = `${programName} - ${userName} 申请文件`;
    const folder = zip.folder(folderName)!;

    preparedDocs.forEach(doc => {
      folder.file(doc.fileName, doc.pdfBlob);
    });

    const zipBlob = await zip.generateAsync({ type: 'blob' });
    saveAs(zipBlob, `${folderName}.zip`);
    addTerminalLog(`[DocPrep] ✓ "${folderName}.zip" 已下载。`);

    addChatMessage({
      id: Date.now().toString(),
      role: 'agent',
      type: 'text',
      content: `✅ 所有申请文件已打包下载！文件夹: "${folderName}"`,
      timestamp: new Date(),
    });
    clearDocPrep();
  };

  const handleDownloadSingle = (doc: PreparedDocument) => {
    downloadBlob(doc.pdfBlob, doc.fileName);
    addTerminalLog(`[DocPrep] 下载: ${doc.fileName}`);
  };

  const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-2xl border bg-background shadow-sm overflow-hidden mx-6 mb-4">
      <div className="bg-primary/5 px-4 py-3 border-b flex items-center gap-2">
        <FileText className="w-4 h-4 text-primary" />
        <span className="text-sm font-semibold text-foreground">文件准备助手 - {programName}</span>
      </div>

      <div className="p-4 space-y-4">
        {/* Step 1: Ask name */}
        {status === 'asking_name' && (
          <div className="space-y-3">
            <div className="flex items-start gap-2">
              <Bot className="w-4 h-4 text-primary mt-0.5" />
              <p className="text-sm text-foreground/90">
                我们现在开始帮您准备 <strong>{programName}</strong> 的申请文件。请先告诉我您的姓名：
              </p>
            </div>
            <div className="flex gap-2">
              <Input
                value={nameInput}
                onChange={e => setNameInput(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleNameSubmit()}
                placeholder="请输入您的姓名"
                className="text-sm"
              />
              <Button size="sm" onClick={handleNameSubmit} disabled={!nameInput.trim()} className="rounded-full px-4">
                <ArrowUp className="w-4 h-4" />
              </Button>
            </div>
          </div>
        )}

        {/* Step 2: Collecting docs one by one */}
        {status === 'collecting_docs' && currentDocIndex < docs.length && (
          <div className="space-y-3">
            <div className="flex items-start gap-2">
              <Bot className="w-4 h-4 text-primary mt-0.5" />
              <div className="text-sm text-foreground/90">
                <p>
                  好的，{userName}！请上传第 <strong>{currentDocIndex + 1}/{docs.length}</strong> 份文件：
                </p>
                <p className="mt-1 font-semibold text-primary">📄 {docs[currentDocIndex]}</p>
                <p className="text-xs text-muted-foreground mt-1">请拍照或上传该文件的图片，我会帮您生成标准PDF。</p>
              </div>
            </div>

            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={handleFileUpload}
            />
            <Button
              variant="outline"
              size="sm"
              className="rounded-full gap-2 w-full"
              onClick={() => fileInputRef.current?.click()}
              disabled={isGenerating}
            >
              {isGenerating ? (
                <>生成中...</>
              ) : (
                <>
                  <Upload className="w-4 h-4" />
                  上传 {docs[currentDocIndex]} 的照片
                </>
              )}
            </Button>
          </div>
        )}

        {/* Prepared docs list */}
        {preparedDocs.length > 0 && (
          <div className="space-y-2">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">已生成文件</p>
            {preparedDocs.map((doc, i) => (
              <div key={i} className="flex items-center gap-2 p-2 rounded-xl bg-accent/20">
                <CheckCircle2 className="w-4 h-4 text-primary flex-shrink-0" />
                <span className="text-xs text-foreground flex-1 truncate">{doc.fileName}</span>
                <button
                  onClick={() => handleDownloadSingle(doc)}
                  className="text-xs text-primary hover:underline flex-shrink-0"
                >
                  下载
                </button>
              </div>
            ))}
          </div>
        )}

        {/* Step 3: All done - download ZIP */}
        {status === 'completed' && preparedDocs.length > 0 && (
          <div className="space-y-3 border-t pt-3">
            <div className="flex items-start gap-2">
              <Bot className="w-4 h-4 text-primary mt-0.5" />
              <p className="text-sm text-foreground/90">
                🎉 所有 {preparedDocs.length} 份文件已准备完毕！点击下方按钮一键下载打包的ZIP文件。
              </p>
            </div>
            <Button
              size="sm"
              className="rounded-full gap-2 w-full"
              onClick={handleDownloadAll}
            >
              <Download className="w-4 h-4" />
              一键下载 {programName} - {userName} 申请文件.zip
            </Button>
          </div>
        )}

        {/* Progress indicator */}
        {status === 'collecting_docs' && (
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <ImageIcon className="w-3 h-3" />
            <span>进度: {preparedDocs.length}/{docs.length} 份文件已完成</span>
            <div className="flex-1 h-1 bg-muted rounded-full overflow-hidden">
              <div
                className="h-full bg-primary rounded-full transition-all"
                style={{ width: `${(preparedDocs.length / docs.length) * 100}%` }}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DocPrepChat;
